prog3/recipebook/config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/recipes' => 'users#recipes', as: 'user_recipes'
  get 'recipes/:id/ingredients' => 'recipes#list_ingredients', as: 'list_ingredients'
  post 'recipes/:id/ingredients' => 'recipes#add_ingredients', as: 'add_ingredients'
  put 'recipes/:id/ingredients/:ingredient_id' => 'recipes#update_ingredients', as: 'update_ingredients'
  get 'recipes/ingredients' => 'recipes#all_ingredients', as: 'all_ingredients'
  delete 'recipes/:id/ingredients/:ingredient_id' => 'recipes#delete_ingredient', as: 'delete_ingredient'
  delete 'recipes/:id/ingredients' => 'recipes#delete_all_ingredients', as: 'delete_all'

  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
end

prog3/recipebook/app/models/recipe.rb
class Recipe < ApplicationRecord


end

prog3/recipebook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  protect_from_forgery

  # GET /recipes
  # GET /recipes.json
  def index
    info = Aws.get_recipes_from_db
    render :json => info
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    response = Aws.list_recipe(params[:id])
    render :json => response
  end

  # GET /recipes/new
  def new

  end

  # GET /recipes/1/edit
  def edit

  end

  # POST /recipes
  # POST /recipes.json
  def create
    name = params['name']
    description = params['description']
    instructions = params['instructions']
    cook_time = params['cook_time']
    quantity = params['quantity']
    serving_size = params['serving_size']
    uid = params['user_id']
    aws_params = Hash.new
    aws_params[:custom_fields] = {
      'name' => name,
      'description' => description,
      'instructions' => instructions,
      'cook_time' => cook_time,
      'quantity' => quantity,
      'serving_size' => serving_size,
      'user_id' => uid
    }
    if Aws.save_recipe_to_db(aws_params)
      msg = {:notice => "Recipe created!"}
      render :json => msg
    else
      msg = {:notice => "Error while save to DynamoDB!"}
      render :json => msg
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    rid = params['id']
    name = params['name']
    description = params['description']
    instructions = params['instructions']
    cook_time = params['cook_time']
    quantity = params['quantity']
    serving_size = params['serving_size']
    uid = params['user_id']
    aws_params = Hash.new
    aws_params[:custom_fields] = {
      'recipe_id' => rid,
      'name' => name,
      'description' => description,
      'instructions' => instructions,
      'cook_time' => cook_time,
      'quantity' => quantity,
      'serving_size' => serving_size,
      'user_id' => uid
    }
    if Aws.update_recipe(aws_params)
      msg = {:notice => "Recipe updated!"}
      render :json => msg
    else
      msg = {:notice => "Error while save to DynamoDB!"}
      render :json => msg
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    rid = params['id']
    if Aws.delete_recipe(rid) && Aws.delete_all_ingredients(rid)
      msg = {:notice => "Recipe deleted!"}
      render :json => msg
    else
      msg = {:notice => "Error while deleting from DynamoDB!"}
      render :json => msg
    end
  end

  # GET /recipes/1/ingredients
  # GET /recipes/1/ingredients.json
  def list_ingredients
    rid = params[:id]
    items = Aws.get_ingredients_from_db(rid)
    render :json => items
  end

  # GET /recipes/ingredients
  def all_ingredients
    items = Aws.get_all_ingredients_from_db
    render :json => items
  end

  # POST recipes/1/ingredients
  # POST /recipes/1/ingredients.json
  def add_ingredients
    rid = params['id']
    name = params['name']
    quant = params['quantity']
    meas = params['measurement']

    ingredients = {
      'name' => name,
      'quantity' => quant,
      'measurement' => meas,
    }

    if Aws.save_ingredient_to_db(rid, ingredients)
      msg = {:notice => "Ingredient created!"}
      render :json => msg
    else
      msg = {:notice => "Error while creating ingredient!"}
      render :json => msg
    end
  end

  # PUT/PATCH recipes/1/ingredients/1
  def update_ingredients
    rid = params['id']
    iid = params['ingredient_id']
    name = params['name']
    quant = params['quantity']
    meas = params['measurement']

    aws_params = Hash.new
    aws_params[:custom_fields] = {
      'recipe_id' => rid,
      'ingredient_id' => iid,
      'name' => name,
      'quantity' => quant,
      'measurement' => meas,
    }

    if Aws.update_ingredient(aws_params)
      msg = {:notice => "Ingredient updated!"}
      render :json => msg
    else
      msg = {:notice => "Error while updating ingredient!"}
      render :json => msg
    end
  end

  # DELETE /recipes/1/
  # DELETE /recipes/1.json
  def delete_all_ingredients
    rid = params['id']

    if Aws.delete_all_ingredients(rid)
      msg = {:notice => "All ingredients deleted!"}
      render :json => msg
    else
      msg = {:notice => "Error while deleting all ingredients!"}
      render :json => msg
    end
  end

  # DELETE /recipes/1/ingredients/1
  def delete_ingredient
    rid = params['id']
    iid = params['ingredient_id']

    if Aws.delete_ingredient(rid, iid)
      msg = {:notice => "Ingredient deleted!"}
      render :json => msg
    else
      msg = {:notice => "Error while deleting ingredient!"}
      render :json => msg
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :instructions, :servings, :cook_time, :published)
  end
end

prog3/recipebook/app/helpers/recipes_helper.rb
module RecipesHelper
end

prog3/recipebook/app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, cols: 50, rows: 10 %>
  </div>

  <div class="field">
    <%= f.label :instructions %>
    <%= f.text_area :instructions %>
  </div>

  <div class="field">
    <%= f.label :servings %>
    <%= f.number_field :servings %>
  </div>

  <div class="field">
    <%= f.label :cook_time_in_minutes %>
    <%= f.number_field :cook_time %>
  </div>

  <div class="field">
    <%= f.label :publish_recipe? %>
    <%= f.check_box :published, { checked: true } %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <%= f.submit "Reset Form", :type => "reset" %>
  </div>
<% end %>

prog3/recipebook/app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

prog3/recipebook/app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <!--<th>Instructions</th>-->
    <!--<th>Servings</th>-->
    <!--<th>Cook time</th>-->
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to(recipe.name, recipe_path(recipe)) %></td>
      <td><%= recipe.description %></td>
      <!--<td><%= recipe.instructions %></td>-->
      <!--<td><%= recipe.servings %> people</td>-->
      <!--<td><%= recipe.cook_time %> minutes</td>-->

      <% if recipe.user_id == current_user.id %>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% else %>
        <td colspan="3"><%= link_to 'Show', recipe %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

prog3/recipebook/app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

prog3/recipebook/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p>
  <strong>Servings:</strong>
  <%= @recipe.servings %>
</p>

<p>
  <strong>Cook time:</strong>
  <%= @recipe.cook_time %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>