prog3/recipebook/config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/recipes' => 'users#recipes', as: 'user_recipes'
  get 'recipes/:id/ingredients' => 'recipes#list_ingredients', as: 'list_ingredients'
  post 'recipes/:id/ingredients' => 'recipes#add_ingredients', as: 'add_ingredients'
  put 'recipes/:id/ingredients/:ingredient_id' => 'recipes#update_ingredients', as: 'update_ingredients'
  get 'recipes/ingredients' => 'recipes#all_ingredients', as: 'all_ingredients'
  delete 'recipes/:id/ingredients/:ingredient_id' => 'recipes#delete_ingredient', as: 'delete_ingredient'
  delete 'recipes/:id/ingredients' => 'recipes#delete_all_ingredients', as: 'delete_all'

  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
end

prog3/recipebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipebook</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-2" id="sidebar">
      <h3>Recipe Retriever</h3>
      <%= link_to("Home", root_path) %><br>
      <% if current_user %>
        <%= link_to("My Profile", user_path(current_user)) %><br>
        <%= link_to("My Recipes", user_recipes_path(current_user)) %><br>
        <%= link_to("Members", users_path) %><br>
        <%= link_to("Logout", logout_path) %>
      <% else %>
        <%= link_to("Login", login_path) %><br>
        <%= link_to("Sign Up", signup_path) %>
      <% end %>
      <div id="spacer"></div>
    </div>
    <div class="col-xs-9">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>