prog3/recipebook/config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/recipes' => 'users#recipes', as: 'user_recipes'
  get 'recipes/:id/ingredients' => 'recipes#list_ingredients', as: 'list_ingredients'
  post 'recipes/:id/ingredients' => 'recipes#add_ingredients', as: 'add_ingredients'
  put 'recipes/:id/ingredients/:ingredient_id' => 'recipes#update_ingredients', as: 'update_ingredients'
  get 'recipes/ingredients' => 'recipes#all_ingredients', as: 'all_ingredients'
  delete 'recipes/:id/ingredients/:ingredient_id' => 'recipes#delete_ingredient', as: 'delete_ingredient'
  delete 'recipes/:id/ingredients' => 'recipes#delete_all_ingredients', as: 'delete_all'

  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
end

prog3/recipebook/app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Validations

  has_many :recipes
  validates :name, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password, presence: true

  has_secure_password
end

prog3/recipebook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :recipes]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(public_profile: true)
    unless current_user
      redirect_to login_path
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if @user.public_profile == false
      redirect_to users_path
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recipes
    @user_recipes = @user.recipes.all
    unless @user_recipes
      redirect_to login_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :public_profile)
    end
end

prog3/recipebook/app/helpers/users_helper.rb
module UsersHelper
end

prog3/recipebook/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, :placeholder => "Username" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => "Password" %>
  </div>
  <div class="field">
    <%= f.label :public_profile %><br/>
    <%= f.label :public_profile, "Yes", :value => "true" %>
    <%= f.radio_button :public_profile, true %>
    <%= f.label :public_profile, "No", :value => "false" %>
    <%= f.radio_button :public_profile, false, :checked => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prog3/recipebook/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

prog3/recipebook/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

prog3/recipebook/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

prog3/recipebook/app/views/users/recipes.html.erb
<p id="notice"><%= notice %></p>

<h1>My Recipes</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
   <% @user_recipes.each do |recipe| %>
     <tr>
       <td><%= link_to(recipe.name, recipe_path(recipe)) %></td>
       <td><%= recipe.description %></td>
       <td><%= link_to 'Show', recipe %></td>
       <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
       <td><%= link_to 'Destroy', recipe, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

prog3/recipebook/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>